#pragma once
#define SOLVER_METHOD_LOS 0
#define SOLVER_METHOD_GMRES 1
#define SOLVER_METHOD_CGM_SYMM 2
#define SOLVER_METHOD_PARDISO 3
#define SOLVER_METHOD_LU 4
#define SOLVER_METHOD_LLT 5

#define SOLVER_DECOMP_TYPE_D 0
#define SOLVER_DECOMP_TYPE_LU 1
#define SOLVER_DECOMP_TYPE_NONE 2

#define SOLVER_MKL_NO 0
#define SOLVER_MKL_YES 1